module.exports = Object.freeze({
    ADMINS_TABLE: "Admins",
    ATTENDANCES_TABLE: "CourseAttendance",
    ATTENDANCES_TICKET_TABLE: "AttendanceTicket",
    CAMPUS_TABLE: "Campuses",
    FEEDBACK_TABLE: "Feedbacks",
    CLASS_TABLE: "Groups",
    COURSEWORK_DETAILS_TABLE: "Coursework_Details",
    COURSES_REGISTRATION_TABLE: "Course_Registration",
    COURSES_TABLE: "Courses",
    DEPARTMENTS_TABLE: "Departments",
    GRADE_TABLE: "Grades",
    LECTURERS_TABLE: "Lecturers",
    PARTICIPANTS_TABLE: "Participants",
    PROGRAMME_TABLE: "Programme",
    REQUEST_TABLE: "Requests",
    ROLES_TABLE: "Roles",
    ROOMS_TABLE: "Rooms",
    SCHEDULE_SLOTS_TABLE: "Schedule_Slots",
    SEMESTERS_TABLE: "Semesters",
    STUDENTS_TABLE: "Students",
    SUBJECTS_TABLE: "Subjects",
    SUBMISSIONS_TABLE: "Assignments",
    SUPPORT_DOCUMENTS_TABLE: "Support_Documents",
    TERM_COURSES_TABLE: "Term_Courses",
    TERMS_TABLE: "Terms",
    MATERIALS_TABLE: "Materials",
});
