module.exports = Object.freeze({
    ADMINS_TABLE: "Admins",
    STUDENTS_TABLE: "Students",
    LECTURERS_TABLE: "Lecturers",
    COURSES_TABLE: "Courses",
    COURSES_REGISTRATION_TABLE: "Course_Registration",
    COURSE_CLASS_TABLE: "Course_Classes",
    SUBMISSIONS_TABLE: "Submissions",
    COURSEWORK_DETAILS_TABLE: "Coursework_Details",
    SUBJECTS_TABLE: "Subjects",
    SUPPORT_DOCUMENTS_TABLE: "Support_Documents",
    SCHEDULE_SLOTS_TABLE: "Schedule_Slots",
    SEMESTERS_TABLE: "Semesters",
    ROOMS_TABLE: "Rooms",
    CAMPUS_TABLE: "Campuses",
    ROLES_TABLE: "Roles",
    DEPARTMENTS_TABLE: "Departments",
    REQUEST_TABLE: "Requests",
    CLASS_TABLE: "Groups",
    PROGRAMME_TABLE: "Programme",
    TERMS_TABLE: "Terms",
});
